services:
  metis:
    build: .
    ports:
      - "8060:8060"
    volumes:
      - ./projects:/projects
      - ./nodes:/nodes
      - /var/run/docker.sock:/var/run/docker.sock

  traefik:
    image: traefik:v2.5
    ports:
      - "8080:8080"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      TRAEFIK_API: "true"
      TRAEFIK_API_DASHBOARD: "true"
      TRAEFIK_API_INSECURE: "true"
    command: --providers.http.endpoint=http://metis:8060/traefik
